### ISSUE TITLE
Modernize system test native makefile scripts 

### ISSUE THREAD

**Issue by Mesbah-Alam** [adoptium/aqa-systemtest#413] opened 2021-03-02 20:33 UTC
We have 3 native makefile scripts in system test: 

1) [Jck tests](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.jck/src/native/makefile) 
2) [Modularity test](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.modularity/src/tests/com.test.jlink/native/makefile) 
3) [Shared Classes tests](https://github.com/eclipse/openj9-systemtest/blob/master/openj9.test.sharedClasses.jvmti/src/native/Makefile)

Each of these makefiles need to be updated every time we have a new platform to support.

We should modernize these scripts and see if they can figure out the platform (and the compiler to use) by themselves  instead of PLATFORM being passed in.  

FYI @llxia

**Comment by lumpfish** [comment] 2021-03-11 13:35
The problem is working out whether to build 32 or 64 bit, wihich is dependent on the jdk being tested.

**Comment by Mesbah-Alam** [comment] 2021-03-11 13:53
@lumpfish  - I have been trying to run the compilation without passing the `m32`, `m64` etc flags and the test seems to be compiling fine.

**Comment by lumpfish** [comment] 2021-03-11 14:05
You mean you tested both a 32 an 64 bit jdk with using the flags and the tests ran OK?
Actually there is only 32 bit arm left now isn't there?  Certainly if all jdks are now 64 bit the problem goes away.

**Comment by Mesbah-Alam** [comment] 2021-03-11 18:56
> You mean you tested both a 32 an 64 bit jdk without using the flags and the tests ran OK on both?

Tested successfully on `win32` (internal Jenkins/Grinder/14131) and `arm` (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7622). The native system tests compile fine without the use of 32 bit specific flags on both. 

Question is, what is the full set of 32 bit platforms that we support ? 

A quick chat with @AdamBrousseau revealed that we support 32 bit on Java 7 and 8 only; and OpenJ9 Win32 JDK8. TKG based system tests do not support Java 7 (yet). So, that leaves us with Java 8 only. 

A not-so-graceful way of course would be to deliver the change and fix any issue after. 

@llxia : would you know if there is a way to test using Java 8 on 32 bit AIX, z/OS, Mac and Linux flavours? Currently the PLATFORM options on Grinder doesn't support these (it only has 32 bit Windows and ARM).

**Comment by smlambert** [comment] 2021-03-12 17:35
While we currently focus on jdk8+, I know there was some discussion of attempting to cover jdk7 testing requirements as well.  After our initial investigation of this (and seeing what additional work would be required), we decided we would not do this.  

I think it is a fair approach to ensure we work well on the existing set of platforms listed in the [PLATFORM_MAP](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_tests#L3) which I believe was created with actual example builds in mind.

The platform map currently contains 6 32-bit platforms, arm_linux, x86-32_windows (which are openly built and supported), and ppc32_aix, ppc32_linux, s390_linux, x86-32_linux   For those last 4 cases, can you check espresso builds for IBM Java 8 builds for SDKs that you could use for testing?  I would not want to remove support for those, if they still exist and given that there was an effort made to move to use AQA tests for those internal to IBM builds.   

One other thing to note, there are 2 statements, "they compile fine" and "there are no newly introduced weird test failures because of compiler arg changes" to consider.  So, for the 2 currently supported 32-bit platforms, as part of a PR check, a full set of tests should be run pre/post this change to check all things look sane.  (and if the other 4 internal platform builds can be verified, even better).

**Comment by Mesbah-Alam** [comment] 2021-03-12 20:29
`sanity.system` started on: 

- Linux ARM / Hotspot JDK8: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7698/ 
- Windows 32 bit / OpenJ9 JDK8: Internal/Grinder/14174
- PPC64LE Linux / OpenJ9 JDK11: Internal/14178
- X64 Windows / OpenJ9 JDK11 : Internal/14182
- AARCH64 Linux: Internal/14177
- PPC64 AIX : Internal/Grinder/14176
- X64 Linux: Internal/Grinder/14180
- X64 OSX: Internal/Grinder/14181
- s390x Linux: Internal/Grinder/14179

- PPC32 AIX :  
- PPC32 Linux :  
- s390 Linux : 
- x86-32 Linux:

**Comment by Mesbah-Alam** [comment] 2021-03-13 00:03
As the changes affect JCK too,`sanity.jck` started on internal Jenkins: 
- X64 Windows:Grinder #14192
- Arch64 Linux: Grinder #14187
- PPC64LE Linux : Grinder #14188
- X64 Linux: Grinder #14190
- PPX64 AIX:  Grinder #14186
- X64 OSX: Grinder #14191
- s390x Linux: Grinder #14189

**Comment by Mesbah-Alam** [comment] 2021-03-14 13:55
The common `jck-runtime-vm-constantpool_0` failure on all platforms, as reported in the comment above, doesn't seem to be related to the updates made for this issue though. 

The failure occurs with test materials from master too (see: internal/Grinder/14210).  

@JasonFengJ9 - could you please check if is this a known JCK failure? (A quick look up in OpenJ9 and Backlog repo doesn't reveal any obvious issue that may be related to this failure).

**Comment by JasonFengJ9** [comment] 2021-03-14 15:23
> The common jck-runtime-vm-constantpool_0 failure on all platforms

This is a known failure as per RTC `145068: JCK 11 failure : jck-runtime-vm-constantpool_0 - Segmentation error vmState=0x00040000` which was introduced around March 10th and fixed in next day.
Pls try a latest build.

**Comment by Mesbah-Alam** [comment] 2021-03-14 15:46
> This is a known failure as per RTC 145068

@JasonFengJ9 - Thanks for the information. Since it's a known failure, we can ignore it as far as verifying the PRs related to this issue is concerned. 

> which was introduced around March 10th and fixed in next day.
Pls try a latest build.

That said, all the above Grinders were run on March 13, 2021 and used OpenJ9 "nightlies" from Adopt. e.g. 

```
12:57:43  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.11+5-202103111808)
12:57:43  Eclipse OpenJ9 VM AdoptOpenJDK (build master-13936a4d3, JRE 11 Linux s390x-64-Bit Compressed References 20210311_911 (JIT enabled, AOT enabled)
12:57:43  OpenJ9   - 13936a4d3
12:57:43  OMR      - 2c0d1393c
12:57:43  JCL      - 8d7fbfd341 based on jdk-11.0.11+5)
12:57:44  =JAVA VERSION OUTPUT END=
12:57:44  =RELEASE INFO BEGIN=
12:57:44  IMPLEMENTOR="AdoptOpenJDK"
12:57:44  IMPLEMENTOR_VERSION="AdoptOpenJDK"
12:57:44  JAVA_VERSION="11.0.11"
12:57:44  JAVA_VERSION_DATE="2021-04-20"
```
It appears that the fix didn't make it into the above SDK and such (yet).

**Comment by JasonFengJ9** [comment] 2021-03-14 19:13
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.11+5-202103111808)

The JVM in question was built on March 11th which has `OpenJ9   - 13936a4d3` and just missed https://github.com/eclipse/openj9/pull/12194/commits/5b422926f74281277bd5c40690ad080d354d8e7f.
Next adopt build should fix the crash referred.

**Comment by smlambert** [comment] 2021-03-17 19:24
3 PRs related to this issue are now merged:
https://github.com/adoptium/aqa-systemtest/pull/415
https://github.com/eclipse/openj9-systemtest/pull/128
https://github.com/adoptium/STF/pull/106

@Mesbah-Alam - thanks for the large amount of testing you did to get to this point.  Believe this issue can now be closed.

**Comment by Mesbah-Alam** [comment] 2021-03-17 19:33
Thanks for reviewing @smlambert and @llxia . 

A good use case would now be to add a new platform (e.g. Alpine Linux) and see how seamlessly the system tests behave. Also, the code block we left intact for Solaris need testing too; something we can do once we have Solaris machines available.

**Comment by smlambert** [comment] 2021-03-17 19:41
New-ish platforms to verify: 

solaris_sparcv9
solaris_x86
Solaris machines are available, work to add testing is being done in this issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/799

alpine-linux: 
The test machines (docker-based) for Alpine-linux was hitting an issue where a Perl module was not present.  Work being done under issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/2223

risc-v: 
Work being done under https://github.com/AdoptOpenJDK/openjdk-tests/issues/2391

FYI @sxa

**Closed by smlambert** 2021-03-17 19:41 UTC
Labels: enhancement
